#define SCREWYHUD_NONE 0
#define SCREWYHUD_CRIT 1
#define SCREWYHUD_DEAD 2
#define SCREWYHUD_OXYGEN 3
#define SCREWYHUD_TOXIN 4

#define SCREWYHUD_POOL list(\
	SCREWYHUD_CRIT,\
	SCREWYHUD_DEAD,\
	SCREWYHUD_OXYGEN,\
	SCREWYHUD_OXYGEN,\
	SCREWYHUD_TOXIN,\
	SCREWYHUD_TOXIN\
	)
